language: node_js

node_js:
  - "10"
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn global add codecov

script:
  - npm run lint
  - npm run testonly:cov && codecov

notifications:
  email:
    on_success: never